package main

import (
	"bytes"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"snippetbox.micypac.io/internal/assert"
)


func TestPing(t *testing.T) {
	// Initialize a new http.ResponseRecorder
	rr := httptest.NewRecorder()

	// Initialize a new dummy http.Request
	r, err := http.NewRequest(http.MethodGet, "/", nil)
	if err != nil {
		t.Fatal(err)
	}

	// Call the ping handler func, passing in the httptest.ResponseRecorder and http.Request
	ping(rr, r)

	// Call the Result() method on the ResponseRecorder to get the response generated by the ping handler.
	rs := rr.Result()

	// Check the status code was 200.
	assert.Equal(t, rs.StatusCode, http.StatusOK)

	
	defer rs.Body.Close()
	
	// Check the response body written by the ping handler equals "OK".
	body, err := io.ReadAll(rs.Body)
	if err != nil {
		t.Fatal(err)
	}

	bytes.TrimSpace(body)

	assert.Equal(t, string(body), "OK")


}
